coverage:
  range: 0..22
  status:
    project:
      default: false
      tests:
        target: 100%
        paths: "tests/"
      app:
        target: 40%
        paths: "!tests/"
    patch: off
ignore:
 - tests/copy/.*
